paths:
  /api/v2/courses:
    get:
      operationId: getCourses
      responses:
        "200":
          $ref: '#/responses/CourseResponse'
      tags:
      - courses
  /api/v2/courses/{id}:
    get:
      operationId: getCourse
      parameters:
      - description: The ID of the course
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/CourseResponse'
      tags:
      - courses
  /api/v2/students:
    get:
      operationId: getStudents
      responses:
        "200":
          $ref: '#/responses/StudentResponse'
      tags:
      - students
  /api/v2/students/{id}:
    get:
      operationId: getStudent
      parameters:
      - description: The ID of the student
        in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/StudentResponse'
      tags:
      - students
responses:
  CourseResponse:
    description: Course represents a ...
    headers:
      id:
        type: string
      title:
        type: string
  StudentResponse:
    description: Student represents a ...
    headers:
      email:
        type: string
      firstname:
        type: string
      id:
        description: |-
          in: path
          required: true
        type: string
      lastname:
        type: string
swagger: "2.0"
